version: 3

build_arg_defaults: 
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: ''

dependencies:
  galaxy: requirements.yml
  python:
    - kubernetes
    - openshift
  system: bindep.txt

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest

additional_build_steps:
  append_final:
    - ADD linux-amd64/helm /usr/local/bin/helm
    - RUN mkdir -p /runner/helm_plugin && chgrp 0 /runner/helm_plugin && chmod -R ug+rwx /runner/helm_plugin
    - ENV HELM_PLUGINS=/home/runner/helm_plugin
    - RUN helm plugin install https://github.com/databus23/helm-diff
